overrides:
  form-data@>=4.0.0 <4.0.6: ">=4.0.6"

allowBuilds:
  "@parcel/watcher": true
  "@scarf/scarf": false
  "@swc/core": true
  "@tree-sitter-grammars/tree-sitter-yaml": true
  core-js-pure: false
  esbuild: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
